apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mimir
  namespace: argocd
spec:
  project: default
  destination:
    namespace: mimir  #update namespace name if you wish
    name: in-cluster   #update cluster name if its different
  source:
    repoURL: https://github.com/patrostkowski/helm-to-argo-migration-poc.git
    targetRevision: "main"
    path: helm/releases/mimir
    helm:
      releaseName: mimir
      valueFiles:
        - common-values.yaml
        - dev-values.yaml
        - project/dev-values.yaml
        - project/dev-values.secret.enc.yaml
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
