apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mimir
  namespace: argocd
spec:
  project: default
  destination:
    namespace: mimir  #update namespace name if you wish
    name: in-cluster   #update cluster name if its different
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: "6.58.8"
    chart: grafana
    helm:
      values: |
        image:
          tag: 9.3.6
        adminPassword: devops123
        ingress:
          enabled: true
